# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-27 23:23
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_id', models.CharField(max_length=30, unique=True)),
                ('source_term', models.TextField(db_index=True)),
                ('note', models.TextField()),
                ('description', models.TextField()),
                ('translations', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
