# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 00:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0089_create_project_manager_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_id', models.CharField(max_length=30, unique=True)),
                ('source_term', models.TextField(db_index=True)),
                ('note', models.TextField()),
                ('description', models.TextField()),
                ('entities', models.ManyToManyField(related_name='terminology_terms', to='base.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='TermTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms_translations', to='base.Locale')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='terminology.Term')),
            ],
        ),
    ]
