# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-30 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0003_auto_20180716_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='library',
            field=models.CharField(choices=[('p', 'pontoon'), ('cl', 'compare-locales')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='warning',
            name='library',
            field=models.CharField(choices=[('p', 'pontoon'), ('cl', 'compare-locales')], db_index=True, max_length=20),
        ),
    ]
